## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  # - osx
  # - windows

julia:
  - 1.3
  - 1.5
  - nightly

matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true

notifications:
  email: false

script: # the default script is equivalent to the following
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia --project -e 'using Pkg; Pkg.build(); Pkg.test(; coverage=true)';

after_success:
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
