name = "Routing"
uuid = "8785b77d-c82c-4bf6-9b42-dddedd117a0f"
authors = ["Changhyun Kwon <chkwon@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"

[compat]
DataStructures = "0.18"
ElasticArrays = "1.2"
GLPK = "0.14"
JuMP = "0.21"
LightXML = "0.9"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "PyPlot", "Random"]
